// Code generated by genast.go; DO NOT EDIT.
package ast

import (
	"fmt"

	"github.com/mkeesey/craftinginterpreters/token"
)

type Visitor[T any] interface {
	VisitBinary(*Binary) T
	VisitGrouping(*Grouping) T
	VisitLiteral(*Literal) T
	VisitUnary(*Unary) T
}

func Visit[T any](expr Expr, visitor Visitor[T]) T {
	switch n := expr.(type) {
	case *Binary:
		return visitor.VisitBinary(n)
	case *Grouping:
		return visitor.VisitGrouping(n)
	case *Literal:
		return visitor.VisitLiteral(n)
	case *Unary:
		return visitor.VisitUnary(n)
	default:
		panic(fmt.Sprintf("Unknown expression type %T", expr))
	}
}

type Expr interface {
	expr()
}

type Binary struct {
	Left Expr
	Operator *token.Token
	Right Expr
}

func (b *Binary) expr() {}

type Grouping struct {
	Expression Expr
}

func (b *Grouping) expr() {}

type Literal struct {
	Value any
}

func (b *Literal) expr() {}

type Unary struct {
	Operator *token.Token
	Right Expr
}

func (b *Unary) expr() {}


