// Code generated by genast.go; DO NOT EDIT.
package ast

import (
	"fmt"
)

type StmtVisitor[T any] interface {
	VisitExpression(*Expression) T
	VisitPrint(*Print) T
}

func VisitStmt[T any](stmt Stmt, visitor StmtVisitor[T]) T {
	switch n := stmt.(type) {
	case *Expression:
		return visitor.VisitExpression(n)
	case *Print:
		return visitor.VisitPrint(n)
	default:
		panic(fmt.Sprintf("Unknown expression type %T", stmt))
	}
}

type Stmt interface {
	stmt()
}

type Expression struct {
	Expression Expr
}

func (b *Expression) stmt() {}

type Print struct {
	Expression Expr
}

func (b *Print) stmt() {}


